### ISSUE TITLE
Could you generate .cow files from the png images and your script?

### ISSUE THREAD

**Issue by Naereen** [dfrankland/pokemonsay#40]
Hi again,
I thought your implementation used [.cow](https://github.com/possatti/pokemonsay/tree/master/cows) files, like the original one, but I see that there are just [PNG](https://github.com/dfrankland/pokemonsay/tree/master/src/images) images in your version.

(The first issue with that is that it clearly violates Nintendo's copyright, but well.. your project is not the only one.)

On the other hand, I see that the output of your script looks very much like the [original project](https://github.com/possatti/pokemonsay/), and I guess the script automatically converts the selected pokemon PNG image to an ASCII version.
By using the script, and maybe processing its output a little bit, I guess/hope that it shouldn't be hard to produce .cow files for each Pokémons.

It could be added in a cow/ folder.
And without changing anything else in your codebase (no need to use the .cow files, if the current process already works fine), they could be used in the original project code too (I have to admit, I don't want to install a second pokemonsay)

**Comment by dfrankland** [comment]
Feel free to make a PR

**Comment by Naereen** [comment]
Sorry I was not saying "can I ..." but "could you .. ?", I won't have time to try this.

**Comment by dfrankland** [comment]
Sorry, I don't have time either
