### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by Naereen** [dfrankland/pokemonsay#41]
Hello there,
I see your project does not have a LICENSE file, and as such it means that it is *not* open-source, but fully copyrighted to you.
Could I suggest that you try to choose an open-source license, and add it?
The [choosealicense.com/](https://choosealicense.com/) can help you do that.
Don't hesitate to ask questions, if you want.
Regards

**Comment by dfrankland** [comment]
MIT
https://github.com/dfrankland/pokemonsay/blob/347876c14043a7f42b03c7511a844c96fa57a1ac/package.json#L18

I'll add a license file soon

**Comment by Naereen** [comment]
Thanks.
Add a LICENSE file would allow GitHub to display it nicely (on the right of the new web interface), and adding a mention on the README would also help.

**Comment by Naereen** [comment]
@dfrankland still no LICENSE file and no mention on the README?

**Comment by dfrankland** [comment]
@Naereen I am open to pull requests

**Comment by Naereen** [comment]
Of course you are, but that's quite lazy. Honestly? You expect a PR just to add a single file?

**Comment by Naereen** [comment]
... done.
